/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * Native introspection handle for the Rust schema registry.
 *
 * JavaScript callables are registered through the `SchemaRegistry` class
 * exported by `@easeo/core`, which stores them and applies the generated
 * schema around the build. This native type only exposes `has` and
 * `listTypes`.
 */
export declare class NodeSchemaRegistry {
  /** Returns whether a native builder is registered for the schema type. */
  has(schemaType: string): boolean
  /** Lists the schema types with a registered native builder. */
  listTypes(): Array<string>
}

/** A generated, machine-readable SEO contract. */
export declare class NodeSeoContract {
  /** Version of the contract format itself. */
  get contractVersion(): string
  /** Generator name. */
  get generatorName(): string
  /** Generator version. */
  get generatorVersion(): string
  /** Site identity stored in the contract. */
  get site(): NodeContractSite
  /** Default expectations applied to every route. */
  get defaults(): NodeSeoExpectation
  /** Route specific rules. */
  get rules(): Array<NodeSeoContractRule>
  /** Per-route expectation overrides. */
  get exceptions(): Record<string, NodeSeoExpectation>
  /** Returns the SHA-256 hash of the serialized contract. */
  hash(): string
  /** Returns the contract as pretty printed JSON. */
  toJSON(): string
  /** Returns the contract as a plain object. */
  toDict(): any
}

/** The resolved, deterministic SEO payload. */
export declare class NodeSeoPayload {
  /** Resolved title. */
  get title(): string
  /** Resolved description. */
  get description(): string
  /** Normalized canonical URL. */
  get canonical(): string
  /** Serialized robots directives, for example `"index,follow"`. */
  get robots(): string
  /** Open Graph metadata. */
  get openGraph(): NodeOpenGraph
  /** Twitter Card metadata. */
  get twitter(): NodeTwitter
  /** Generated JSON-LD, when schema generation is enabled. */
  get schemaJsonLd(): any | null
  /** Extra fields added by config-scoped hooks. */
  get extra(): Record<string, any>
  /**
   * Renders the full head snippet: title, description, canonical, robots,
   * Open Graph, Twitter Cards, and JSON-LD.
   */
  renderHtml(): string
  /** Renders only the Open Graph meta tags. */
  renderOpengraph(): string
  /** Renders only the Twitter Card meta tags. */
  renderTwitter(): string
  /** Renders only the JSON-LD script tag. */
  renderJsonld(): string
  /** Returns the payload as a pretty printed JSON string. */
  toJSON(): string
  /** Returns the payload as a plain object. */
  toObject(): any
  /** Returns the SHA-256 hash of the payload. */
  hash(): string
  /** Returns the payload hash as a quoted HTTP ETag. */
  etag(): string
}

/** Builds a machine-readable SEO contract. */
export declare function buildSeoContract(config: NodeSeoContractConfig): NodeSeoContract

/** Builds a deterministic SEO payload for an entity at a route. */
export declare function buildSeoPayload(entity: NodeSeoEntity, route: string, config: NodeSeoConfig): NodeSeoPayload

/** Builds a deterministic SEO payload with explicit overrides. */
export declare function buildSeoPayloadWithOverrides(entity: NodeSeoEntity, route: string, config: NodeSeoConfig, overrides: NodeSeoOverrides): NodeSeoPayload

/** Removes tracking parameters from a query string. */
export declare function cleanQuery(query: string): string

/** Removes tracking parameters from a URL. */
export declare function cleanUrl(url: string): NodeCleanResult

/** Returns the native schema registry introspection handle. */
export declare function getSchemaRegistry(): NodeSchemaRegistry

/** A single entry in a breadcrumb trail. */
export interface NodeBreadcrumb {
  /** Human readable label for the breadcrumb. */
  name: string
  /** URL the breadcrumb links to. */
  url: string
}

/** Result of cleaning a URL's tracking parameters. */
export interface NodeCleanResult {
  /** URL with tracking parameters removed. */
  url: string
  /** Parameters that were removed, keyed by parameter name. */
  removedParams: Record<string, string>
  /** Parameters that were kept, keyed by parameter name. */
  cleanedParams: Record<string, string>
}

/** Site identity stored in a contract. */
export interface NodeContractSite {
  /** Canonical hostname. */
  canonicalHost: string
  /** URL scheme. */
  scheme: string
}

/** A single question and answer pair for FAQ schemas. */
export interface NodeFaqItem {
  /** The question text. */
  question: string
  /** The answer text. */
  answer: string
}

/** Open Graph metadata for a payload. */
export interface NodeOpenGraph {
  /** Open Graph object type, for example `"article"` or `"website"`. */
  type: string
  /** Open Graph title. */
  title?: string
  /** Open Graph description. */
  description?: string
  /** Open Graph canonical URL. */
  url?: string
  /** Absolute URL of the Open Graph image. */
  image?: string
  /** Open Graph image width in pixels. */
  imageWidth?: number
  /** Open Graph image height in pixels. */
  imageHeight?: number
  /** Open Graph image alternative text. */
  imageAlt?: string
  /** Site name. */
  siteName?: string
  /** Locale, for example `"en_US"`. */
  locale?: string
  /** Alternate locales. */
  localeAlternate?: Array<string>
  /** Open Graph audio URL. */
  audio?: string
  /** Open Graph video URL. */
  video?: string
}

/** Site-wide configuration for payload generation. */
export interface NodeSeoConfig {
  /** Canonical hostname without a scheme, for example `"example.com"`. */
  canonicalHost: string
  /** Full base URL for path resolution, for example `"https://example.com"`. */
  publicBaseUrl: string
  /** Site name for `og:site_name` and title templates. */
  siteName?: string
  /** Title template containing `{title}`. */
  titleTemplate?: string
  /** Fallback Open Graph image URL. */
  defaultOgImage?: string
  /** Rewrite `http` to `https`. Defaults to `true`. */
  enforceHttps?: boolean
  /** Lowercase path segments. Defaults to `false` (preserve case). */
  lowercasePaths?: boolean
  /** Trailing slash policy: `"always"`, `"never"`, or `"preserve"`. */
  trailingSlash?: string
  /** Collapse repeated slashes. Defaults to `true`. */
  collapseDuplicateSlashes?: boolean
  /** Remove tracking parameters. Defaults to `true`. */
  stripTrackingParams?: boolean
  /**
   * Query parameters to keep when tracking parameters are stripped. A
   * listed parameter is kept even when it matches a tracking pattern.
   */
  allowedQueryParams?: Array<string>
  /** Additional query parameter names to strip, on top of the built-in list. */
  extraTrackingParams?: Array<string>
  /** Open Graph locale, for example `"en_US"`. */
  locale?: string
  /** Alternate locales. */
  localeAlternate?: Array<string>
  /** Twitter `@handle` for `twitter:site`. */
  twitterSite?: string
  /** Organization or publisher name used in schemas. */
  publisherName?: string
  /** Publisher logo URL used in schemas. */
  publisherLogo?: string
  /** Generate JSON-LD from the entity type. Defaults to `true`. */
  autoGenerateSchema?: boolean
  /** Emit `console.warn` for validation issues. Defaults to `false`. */
  emitWarnings?: boolean
  /** Default `index` directive for regular pages. Defaults to `true`. */
  defaultRobotsIndex?: boolean
  /** Default `follow` directive for regular pages. Defaults to `true`. */
  defaultRobotsFollow?: boolean
  /** `index` directive for search pages. Defaults to `false`. */
  searchRobotsIndex?: boolean
  /** `follow` directive for search pages. Defaults to `true`. */
  searchRobotsFollow?: boolean
  /** JSON object mapping entity types to schema.org types. */
  schemaTypeMapJson?: string
  /** Search URL template for the homepage `WebSite` `SearchAction`. */
  searchUrlTemplate?: string
}

/** Input configuration for building a contract. */
export interface NodeSeoContractConfig {
  /** Canonical hostname without a scheme. */
  canonicalHost: string
  /** URL scheme, defaults to `"https"`. */
  scheme?: string
  /** Default expectations applied to every route. */
  defaults?: NodeSeoExpectation
  /** Route specific rules. */
  rules?: Array<NodeSeoContractRule>
  /** JSON object of per-route expectation overrides. */
  exceptionsJson?: string
}

/** A contract rule matched against route paths. */
export interface NodeSeoContractRule {
  /** Route pattern, for example `"/blog/*"`. */
  match: string
  /** Expectations applied when the pattern matches. */
  expect: NodeSeoExpectation
  /** Optional severity: `"error"`, `"warning"`, or `"info"`. */
  severity?: string
}

/** A content entity to generate SEO metadata for. */
export interface NodeSeoEntity {
  /**
   * One of `home`, `post`, `page`, `video`, `taxonomy`, `search`,
   * `product`, `organization`, `local_business`, `faq`, or `other`.
   */
  entityType: string
  /** Page title. */
  title?: string
  /** Short description. `description` is an alias. */
  excerpt?: string
  /** Alias for `excerpt`. */
  description?: string
  /** URL slug. */
  slug?: string
  /** Full content as HTML, used to derive a snippet when no excerpt is set. */
  bodyHtml?: string
  /**
   * Publication status. `"published"` (case-insensitive) keeps the page
   * indexable; any other value becomes noindex.
   */
  status?: string
  /** Absolute URL of the primary image. */
  image?: string
  /** Primary image width in pixels. */
  imageWidth?: number
  /** Primary image height in pixels. */
  imageHeight?: number
  /** Primary image alternative text. */
  imageAlt?: string
  /** Publication date as an ISO date or datetime. */
  publishedAt?: string
  /** Last update date as an ISO date or datetime. */
  updatedAt?: string
  /** Author display name. */
  authorName?: string
  /** Product stock keeping unit. */
  sku?: string
  /** Product price as a string. */
  price?: string
  /** ISO currency code for the price. */
  priceCurrency?: string
  /** Product availability, for example `"InStock"`. */
  availability?: string
  /** Additional URLs used as `sameAs` in organization schemas. */
  sameAs?: Array<string>
  /** Postal address for local business schemas. */
  address?: string
  /** Breadcrumb trail. */
  breadcrumbs?: Array<NodeBreadcrumb>
  /** Question and answer pairs for FAQ schemas. */
  faqItems?: Array<NodeFaqItem>
}

/** Expectations applied to a page, a rule match, or contract defaults. */
export interface NodeSeoExpectation {
  /** The field must be present. */
  required?: boolean
  /** The field must be absent. */
  forbidden?: boolean
  /** The field must equal this value. */
  equals?: string
  /** The field must not equal this value. */
  notEquals?: string
  /** The field must contain this substring. */
  contains?: string
  /** The field must match this regular expression. */
  matches?: string
  /** The field must be one of these values. */
  oneOf?: Array<string>
  /** Minimum string length. */
  minLength?: number
  /** Maximum string length. */
  maxLength?: number
  /** Minimum number of items. */
  minItems?: number
  /** Maximum number of items. */
  maxItems?: number
  /** Whether the page must be indexable. */
  indexable?: boolean
  /** Expected canonical behavior, for example `"self"`. */
  canonical?: string
  /** Whether a JSON-LD schema must be present. */
  schemaRequired?: boolean
  /** Required schema.org types. */
  schemaTypes?: Array<string>
  /** Whether Open Graph metadata must be present. */
  ogRequired?: boolean
  /** Whether Twitter Card metadata must be present. */
  twitterRequired?: boolean
  /** Whether a sitemap entry must be present. */
  sitemapRequired?: boolean
  /** Whether hreflang annotations must be present. */
  hreflangRequired?: boolean
  /** Nested expectations for the title. */
  title?: any
  /** Nested expectations for the description. */
  description?: any
}

/** A single validation finding. */
export interface NodeSeoIssue {
  /** Stable rule identifier, for example `"EASEO101"`. */
  ruleId: string
  /** Severity: `"error"`, `"warning"`, or `"info"`. */
  severity: string
  /** Human readable description of the finding. */
  message: string
  /** Canonical URL the finding applies to. */
  url?: string
  /** Additional structured details about the finding. */
  details: Record<string, any>
}

/** Per-call overrides that take precedence over the entity and config. */
export interface NodeSeoOverrides {
  /** Overrides the resolved title. */
  metaTitle?: string
  /** Overrides the resolved description. */
  metaDescription?: string
  /**
   * Overrides the resolved canonical URL. Trusted: used as-is after an
   * absolute `http(s)` URL check, bypassing the URL policy.
   */
  canonicalUrl?: string
  /**
   * Overrides the route used to build the canonical URL, through the full
   * URL normalization pipeline. Ignored when `canonical_url` is set.
   */
  canonicalPath?: string
  /** Overrides the robots `index` directive. */
  robotsIndex?: boolean
  /** Overrides the robots `follow` directive. */
  robotsFollow?: boolean
  /** Overrides the robots `max-snippet` directive. */
  robotsMaxSnippet?: number
  /** Overrides the robots `max-image-preview` directive. */
  robotsMaxImagePreview?: string
  /** Overrides the robots `max-video-preview` directive. */
  robotsMaxVideoPreview?: number
  /** Overrides the Open Graph title. */
  ogTitle?: string
  /** Overrides the Open Graph description. */
  ogDescription?: string
  /** Overrides the Open Graph image URL. */
  ogImageUrl?: string
  /** Open Graph image width in pixels. */
  ogImageWidth?: number
  /** Open Graph image height in pixels. */
  ogImageHeight?: number
  /** Open Graph image alternative text. */
  ogImageAlt?: string
  /** Overrides the Twitter Card type. */
  twitterCard?: string
  /** Overrides the Twitter title. */
  twitterTitle?: string
  /** Overrides the Twitter description. */
  twitterDescription?: string
  /** Overrides the Twitter image URL. */
  twitterImageUrl?: string
  /** Replaces the generated JSON-LD schema. */
  schemaJsonld?: any
  /** When `true`, no JSON-LD is emitted. */
  omitSchema?: boolean
  /** When `true`, the config title template is skipped. */
  skipTitleTemplate?: boolean
  /** Overrides the Twitter creator handle. */
  twitterCreator?: string
  /** Open Graph audio URL. */
  ogAudio?: string
  /** Open Graph video URL. */
  ogVideo?: string
}

/** Twitter Card metadata for a payload. */
export interface NodeTwitter {
  /** Card type, for example `"summary_large_image"`. */
  card: string
  /** Twitter title. */
  title?: string
  /** Twitter description. */
  description?: string
  /** Absolute URL of the Twitter image. */
  image?: string
  /** Twitter image alternative text. */
  imageAlt?: string
  /** Twitter `@handle` for the site. */
  site?: string
  /** Twitter `@handle` of the content creator. */
  creator?: string
}

/** Normalizes a route path according to the given policy fields. */
export declare function normalizePath(path: string, enforceHttps?: boolean | undefined | null, lowercasePaths?: boolean | undefined | null, trailingSlash?: string | undefined | null, collapseDuplicateSlashes?: boolean | undefined | null, stripTrackingParams?: boolean | undefined | null, allowedQueryParams?: Array<string> | undefined | null, extraTrackingParams?: Array<string> | undefined | null): string

/** Resolves a path or URL against the configured public base URL. */
export declare function normalizePublicUrl(urlOrPath: string, config: NodeSeoConfig): string

/**
 * Rebuild a payload from its wire dict. Used by the JS hook layer, which
 * post-processes `toObject()` and needs the result to flow back into
 * `hash()`, `renderHtml()`, `etag()`, etc.
 */
export declare function payloadFromDict(dict: any): NodeSeoPayload

/** Runs the built-in validation checks against a payload. */
export declare function validatePayload(payload: NodeSeoPayload): Array<NodeSeoIssue>
